# site settings
title: Hee Seung Kim
subtitle: Physics
email: usami.kim@gmail.com
description: Exploring quantum matter through theory and computation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hee-seung-kim.github.io" # the base hostname & protocol for your site
author: Hee Seung Kim
street_address: 291 Daehak-ro
city: Yuseong-gu
state: Daejeon
zip_code: 34141
country: Republic of Korea
phone: +82-10-****-****

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/Hee-Seung-Kim
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter: https://x.com/usami_kim
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- generic.md
- elements.md
